### ISSUE TITLE
attacked large graphs available?

### ISSUE THREAD

**Issue by Chenhui1016** [sigeisler/robustness_of_gnns_at_scale#1] opened 2021-12-13 21:14 UTC
Hi there,

Thanks for the great work! I'm wondering if you could kindly provide the attacked graphs of ogbn-arxiv and ogbn-product datasets?

Best,
Chenhui

**Comment by TobiasSchmidtDE** [comment] 2021-12-14 08:29
Hi Chenhui,

we're happy to help you out. But could you quickly eleborate on what exactly you mean with the "attacked graphs of ogbn-arxiv / ogbn-products".

The clean / unperturbed grahps you can find at the [OGBN website](https://ogb.stanford.edu/docs/nodeprop/)

We will also update this repository with a more up-to-date version of the code some time today

Best, Tobias

**Comment by Chenhui1016** [comment] 2021-12-14 13:35
Hi Tobias,

Thanks for the reply! I mean the graphs that are attacked by PR-BCD (under the poison setting). My gpu memory only has 11G and probably cannot run PR-BCD on relatively large graphs such as ogbn-arxiv and ogbn-products, which is why I hope you could kindly provided those attacked graphs, so that I can evaluate robustness of other GNN models on them.

Looking forward to your updated code! Thanks for the great work again!

**Comment by sigeisler** [comment] 2021-12-14 13:40
Hi @Chenhui1016,

we will provide the perturbed graphs soon. Anyhow, we ran most of the ogbn-arxiv experiments also on a 11GB GPU. So for ogbn-arxiv you should be good to go.

Please note that we only experimented with global attacks (i.e. lowering accuracy over all nodes) for evasion. But you could simply use these perturbed matrices to train a model. At least for the local attacks, this works very well.

Best,
Simon

**Comment by TobiasSchmidtDE** [comment] 2021-12-14 14:10
@Chenhui1016 

We're still working on cleaning up the camera-ready version of the code even further. But we've already pushed the most up-to-date version for you to try out and test. Just have a look at the `camera-ready` branch of this repo. 

If you're having trouble running the code please let us know, so we can keep improving the codebase.

**Comment by Chenhui1016** [comment] 2021-12-14 19:01
Hi Tobias,

I just tried to run the code after following the instruction to install packages, but got a couple of errors below: 

1. The package `rgnn_at_scale.helper` is not included. I manually add `__init__.py` in `rgnn_at_scale/helper` to fix it.
2. When running `pytest tests`, it shows `TypeError: scatter_softmax() got an unexpected keyword argument 'eps'` for aggregation_test and `ModuleNotFoundError: No module named 'experiments'` for experiments_test.
3. There is a typo in the command: `python script_execute_experiment.py --config-files 'config/train/cora_and_citeseer.yaml'`. It should be `python script_execute_experiment.py --config-file 'config/train/cora_and_citeseer.yaml'`
4. When running the corrected command above, it shows the error: `TypeError: expected str, bytes or os.PathLike object, not list` when reading the config file in `helper/local_util.py`

Any suggestions would be greatly appreciated.

**Comment by TobiasSchmidtDE** [comment] 2021-12-16 14:53
Hi @Chenhui1016, 

Thanks a lot for your feedback and helpful notes.
I've pushed a few fixes to the `camera-ready` branch including the `__init__.py` for `rgnn_at_scale/helper`, the typo in the readme and the fix for the TypeError in `helper/local_util.py`.

However, I couldn't reproduce the 2. bug with the TypeError in `scatter_softmax()`. My best guess is that you're using a different version of torch and hence a different version of the `torch_scatter` package. So the signature of the function could be different resulting in the error. 
Please make sure that you're using the same versions of all the dependencies and that your pytest is configured to use the correct python environment. E.g. you need to set the PythonPath for pytest manually. 

Please let us know when you find any other bugs or issues.

**Comment by Xiuyu-Li** [comment] 2022-01-13 03:07
Hi Tobias,

I also got the 2. bug with the TypeError in `scatter_softmax()`. I am wondering which `torch_scatter` version you used? Thanks!

**Comment by TobiasSchmidtDE** [comment] 2022-01-16 17:37
Hi @Xiuyu-Li, 

I've been using torch version `1.8.1+cu102` and torch_scatter version `2.0.7`. 

Hope this helps.

**Comment by Wangbeibei-AHU** [comment] 2022-11-17 07:35
Thanks for your great work!  I want to ask you some questions. I am confusing how to obtain the attacked ogb-arxiv dataset generated by PR-BCD under the poison setting.

**Comment by double-wbb** [comment] 2022-11-17 07:42
Thanks for your great work! I want to ask you some questions. I am confusing how to obtain the attacked ogb-arxiv dataset generated by PR-BCD under the poison setting.  Or, can you  provide the attacked ogb-arxiv dataset?

Looking forward to your reply!

**Comment by sigeisler** [comment] 2022-11-17 09:08
In the paper, we only have evasion experiments on `ogbn-arxiv`. However, a widely adopted strategy is to transfer evasion attacks to poisoning (i.e. use the perturbed adjacency matrix obtained from an evasion attack for training a model from scratch). This is done by Nettack, SGA, ... and so can you do the same with GRBCD or PRBCD.

For a discussion of implications, I would look into the Metattack paper. Naturally, perturbations obtained specifically for poisoning are quite different. If you want to perform a poisoning attack then you might want to look into the example of the current [PytorchGeometric Pull Request](https://github.com/pyg-team/pytorch_geometric/pull/5972/files#diff-481cf8987553762c276802e9f867632fb4e097872b511d7d8202322b5b2f1021). However, I doubt that this example (i.e. without `torch.checkpoint` for the adjacency normalization) will scale to `ogbn-arxiv` out of the box. If you run into trouble I am happy to help.

**Comment by sigeisler** [comment] 2022-11-17 09:54
@Chenhui1016 @Wangbeibei-AHU please see https://github.com/sigeisler/robustness_of_gnns_at_scale/tree/clean for the download instructions (will be merged to master soon)

**Closed as completed** 2022-11-17 11:30 UTC
